"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/producer/tasks"

ENDPOINTS = {
    "producer_generate_audios": {
        "method": "POST",
        "path": "/producer/audios",
        "operation": "generate",
        "schema": {
            "type": "object",
            "required": ["action", "lyric", "prompt"],
            "properties": {
                "lyric": {"type": "string"},
                "model": {
                    "enum": [
                        "FUZZ-2.0 Pro",
                        "FUZZ-2.0",
                        "FUZZ-2.0 Raw",
                        "FUZZ-1.1 Pro",
                        "FUZZ-1.0 Pro",
                        "FUZZ-1.0",
                        "FUZZ-1.1",
                        "FUZZ-0.8",
                    ],
                    "type": "string",
                },
                "title": {"type": "string"},
                "action": {
                    "enum": [
                        "generate",
                        "cover",
                        "extend",
                        "variation",
                        "swap_vocals",
                        "swap_instrumentals",
                        "replace_section",
                        "stems",
                    ],
                    "type": "string",
                },
                "custom": {"type": "boolean"},
                "prompt": {"type": "string"},
                "audio_id": {"type": "string"},
                "continue_at": {"type": "number"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
                "seed": {"type": "string"},
                "instrumental": {"type": "boolean"},
                "sound_strength": {"type": "number"},
                "lyrics_strength": {"type": "number"},
                "weirdness": {"type": "number"},
                "replace_section_end": {"type": "number"},
                "replace_section_start": {"type": "number"},
            },
        },
        "properties": {
            "lyric": {"type": "string"},
            "model": {
                "enum": [
                    "FUZZ-2.0 Pro",
                    "FUZZ-2.0",
                    "FUZZ-2.0 Raw",
                    "FUZZ-1.1 Pro",
                    "FUZZ-1.0 Pro",
                    "FUZZ-1.0",
                    "FUZZ-1.1",
                    "FUZZ-0.8",
                ],
                "type": "string",
            },
            "title": {"type": "string"},
            "action": {
                "enum": [
                    "generate",
                    "cover",
                    "extend",
                    "variation",
                    "swap_vocals",
                    "swap_instrumentals",
                    "replace_section",
                    "stems",
                ],
                "type": "string",
            },
            "custom": {"type": "boolean"},
            "prompt": {"type": "string"},
            "audio_id": {"type": "string"},
            "continue_at": {"type": "number"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
            "seed": {"type": "string"},
            "instrumental": {"type": "boolean"},
            "sound_strength": {"type": "number"},
            "lyrics_strength": {"type": "number"},
            "weirdness": {"type": "number"},
            "replace_section_end": {"type": "number"},
            "replace_section_start": {"type": "number"},
        },
        "parameters": [],
        "defaults": {"model": "FUZZ-2.0", "action": "generate"},
        "fixed": {},
        "allow_empty": ["lyric", "prompt"],
        "query_actions": [],
        "media_response": False,
    },
    "producer_generate_lyrics": {
        "method": "POST",
        "path": "/producer/lyrics",
        "operation": "lyrics",
        "schema": {
            "type": "object",
            "required": ["prompt"],
            "properties": {"prompt": {"type": "string"}},
        },
        "properties": {"prompt": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "producer_upload_reference_audio": {
        "method": "POST",
        "path": "/producer/upload",
        "operation": "upload",
        "schema": {
            "type": "object",
            "required": ["audio_url"],
            "properties": {"audio_url": {"type": "string"}},
        },
        "properties": {"audio_url": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "producer_get_video": {
        "method": "POST",
        "path": "/producer/videos",
        "operation": "video",
        "schema": {
            "type": "object",
            "required": ["audio_id"],
            "properties": {"audio_id": {"type": "string"}},
        },
        "properties": {"audio_id": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "producer_get_wav": {
        "method": "POST",
        "path": "/producer/wav",
        "operation": "wav",
        "schema": {
            "type": "object",
            "required": ["audio_id"],
            "properties": {"audio_id": {"type": "string"}},
        },
        "properties": {"audio_id": {"type": "string"}},
        "parameters": [],
        "defaults": {},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": False,
    },
    "producer_task_retrieve": {
        "method": "POST",
        "path": "/producer/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "producer_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/producer/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
            },
            "required": ["action", "ids"],
        },
        "properties": {
            "id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "action": {"enum": ["retrieve", "retrieve_batch"], "type": "string"},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
